{"name": "Проверка получения ошибки при создании одинковых курьеров", "status": "passed", "start": 1723111273037, "stop": 1723111273287, "uuid": "05138d4e-f5b4-4059-9efe-cd87e25a7e92", "historyId": "4f8eddac56512499110566e1d51cfb02", "testCaseId": "4f8eddac56512499110566e1d51cfb02", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_couriers_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Nightingales-MacBook-Air.local"}, {"name": "thread", "value": "2738-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}